spring.datasource.url=jdbc:mysql://terraform-20250220101013242000000007.c3wwugsckryn.us-east-1.rds.amazonaws.com:3306/springbackend?useSSL=false
spring.datasource.username=admin
spring.datasource.password=Redhat123

spring.jpa.generate-ddl=true
